name: Python application
on:
  workflow_dispatch:
  schedule:
  # 日本時間の午前5時、6時、7時に設定
    -crone: '0 20,21,22 * * *'
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install get-chrome-driver --upgrade
          pip install -r requirements.txt
      - name: Install font
        run: |
          sudo apt install fonts-ipafont
      - name: Run script
        run: |
        python main.py
      - name: git setting
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit files
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git add .
            git commit -m "ファイル更新" -a
            git push
          fi
          
